#!/bin/bash

# help
function helps(){
    echo "my ip"
    echo "	查看本机出口ip地址"
    echo "my info"
    echo "	查看本机信息"
    echo "my net"
    echo "	查看本机网络是否正常"
    echo "my help"
    echo "	查看帮助信息"
}

# check curl
function check_curl(){
    if ( command -v curl > /dev/null ); then

    else
        echo "curl not found, please install curl"
    fi
}
# check ipaddr
function ip(){
    if ( command -v curl > /dev/null ); then
        curl myip.ipip.net
    else
        echo "curl not found, please install curl"
    fi
}

# install neofetch
function yum_install_neo(){
   curl -o /etc/yum.repos.d/konimex-neofetch-epel-7.repo https://copr.fedorainfracloud.org/coprs/konimex/neofetch/repo/epel-7/konimex-neofetch-epel-7.repo && dnf install neofetch -y && clear && neofetch
}
function check_system_and_install_neo(){
    if(command -v apt > /dev/null); then
       sudo apt update -y &&sudo  apt install neofetch curl -y
    elif(command -v yum > /dev/null);then
       sudo yum_install_neo
    elif(command -v dnf > /dev/null);then
       sudo dnf install neofetch curl -y
    elif(command -v zypper> /dev/null);then
       sudo zypper install neofetch -y
    elif(command -v pacman> /dev/null);then
       sudo pacman -Syy && sudo pacman -S neofetch 
    else 
       echo "This system is not supported"
    fi
}

# start neofetch
function neo(){
    if ( command -v neofetch > /dev/null); then
      # echo "install sucessful"
      neofetch
    else
      # echo "ref install"
      check_system_and_install_neo
    fi
}

# ping g.cn
function network(){
    if (ping -c 2 g.cn > /dev/null); then
        echo "网络连接正常"
    else
        echo "网络不可达,请检查网络!!!"
    fi
}

# main
function main(){
check_curl
case $1 in
     ip | IP)
          ip ;;
     info | INFO)
          neo;;
     net | network | NETWORK)
          network;;
     *)
          helps;;
esac

}
main $1
